name: Generate and deploy
on: push
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and build
        run: |
          pip install Jinja2 toml
          ./build.sh
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
